config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("kanban/", include("kanban.urls")),
    path('kanban/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

kanban/urls.py
from django.urls import path
from . import views

app_name = "kanban"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.HomeView.as_view(), name="home"),
    path('signup/', views.signup, name='signup'),
    path("users/<int:pk>/",views.UserDetailView.as_view(),name="users_detail"),
    path("users/<int:pk>/update/", views.UserUpdateView.as_view(), name="users_update"),
    path("lists/",views.ListListView.as_view(),name="lists_list"),
    path("lists/create/",views.ListCreateView.as_view(),name="lists_create"),
    path("lists/<int:pk>/",views.ListDetailView.as_view(),name="lists_detail"),
    path("lists/<int:pk>/update/",views.ListUpdateView.as_view(),name="lists_update"),
    path("lists/<int:pk>/delete/",views.ListDeleteView.as_view(),name="lists_delete"),
    path("cards/create/",views.CardCreateView.as_view(),name="cards_create"),
    path("cards/",views.CardListView.as_view(),name="cards_list"),
    path("cards/<int:pk>/",views.CardDetailView.as_view(),name="cards_detail"),
    path("cards/<int:pk>/update/",views.CardUpdateView.as_view(),name="cards_update"),
    path("cards/<int:pk>/delete",views.CardDeleteView.as_view(),name="cards_delete"),
]

kanban/models.py
from django.db import models
from django.contrib.auth.models import User

class List(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Card(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    list=models.ForeignKey(List,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

kanban/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import List,Card


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ("username", "last_name", "first_name", "email",)



class ListForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ListForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = List
        fields = ("title",)



class CardForm(forms.ModelForm):
    class Meta:
        model=Card
        fields=("title","description","list")

    # def __init__(self, *args, **kwargs):
    #     super(CardForm, self).__init__(*args, **kwargs)
    #     for field_name, field in self.fields.items():
    #         field.widget.attrs['class'] = 'form-control'

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(CardForm, self).__init__(*args, **kwargs)
        self.fields['list'].queryset = List.objects.filter(user=user)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

kanban/views.py
from django.db import models
from django.shortcuts import render,redirect,resolve_url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView,UpdateView,CreateView,ListView,DeleteView
from django.urls import reverse_lazy

from .forms import UserForm,ListForm,CardForm
from .mixins import OnlyYouMixin
from .models import List,Card


def index(request):
    return render(request, "kanban/index.html")


class HomeView(LoginRequiredMixin,ListView):
    model=List
    template_name = "kanban/home.html"
    
    def get_queryset(self):
        return List.objects.filter(user=self.request.user)


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user_instance = form.save()
            login(request, user_instance)
            return redirect("kanban:home")
    else:
        form = UserCreationForm()

    context = {
        "form": form
    }
    return render(request, 'kanban/signup.html', context)


class UserDetailView(OnlyYouMixin, DetailView):
    model = User
    template_name = "kanban/users/detail.html"


class UserUpdateView(OnlyYouMixin,UpdateView):
    model = User
    template_name = "kanban/users/update.html"
    form_class = UserForm

    def get_success_url(self):
        return resolve_url('kanban:users_detail', pk=self.kwargs['pk'])


class ListCreateView(LoginRequiredMixin, CreateView):
    model = List
    template_name = "kanban/lists/create.html"
    form_class = ListForm
    success_url = reverse_lazy("kanban:lists_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ListListView(LoginRequiredMixin,ListView):
    model = List
    template_name = "kanban/lists/list.html"
    
    def get_queryset(self):
        return List.objects.filter(user=self.request.user)


class ListDetailView(LoginRequiredMixin,DetailView):
    model=List
    template_name="kanban/lists/detail.html"


class ListUpdateView(LoginRequiredMixin,UpdateView):
    model=List
    template_name="kanban/lists/update.html"
    form_class=ListForm
    success_url = reverse_lazy("kanban:home")

class ListDeleteView(LoginRequiredMixin,DeleteView):
    model=List
    template_name="kanban/lists/delete.html"
    success_url=reverse_lazy("kanban:home")


class CardCreateView(LoginRequiredMixin,CreateView):
    model=Card
    template_name="kanban/cards/create.html"
    form_class=CardForm
    success_url=reverse_lazy("kanban:home")
    
    def get_form_kwargs(self):
        kwargs = super(CardCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self,form):
        form.instance.user=self.request.user
        return super().form_valid(form)


class CardListView(LoginRequiredMixin,ListView):
    model=Card
    template_name="kanban/cards/list.html"
    
    def get_queryset(self):
        return Card.objects.filter(user=self.request.user)


class CardDetailView(LoginRequiredMixin, DetailView):
    model = Card
    template_name = "kanban/cards/detail.html"


class CardUpdateView(LoginRequiredMixin, UpdateView):
    model = Card
    template_name = "kanban/cards/update.html"
    form_class = CardForm
    success_url = reverse_lazy("kanban:home")
    
    def get_form_kwargs(self):
        kwargs = super(CardUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs



class CardDeleteView(LoginRequiredMixin, DeleteView):
    model = Card
    template_name = "kanban/cards/delete.html"
    success_url = reverse_lazy("kanban:home")

kanban/templates/kanban/base.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'kanban/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arvo&family=Yomogi&display=swap" rel="stylesheet">


    <title>todo</title>

    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light py-3 fixed-top">

                {% if request.user.is_authenticated %}
                <a class=" logo navbar-brand font-weight-bold" href="{% url 'kanban:home' %}">My Todo List <i class="fas fa-cat"></i></a>
                {% else %}
                <a class="logo navbar-brand" href="{% url 'kanban:index' %}">My Todo List <i class="fas fa-cat"></i></a>
                {% endif %}

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                    </ul>

                    <ul class="navbar-nav">

                        {% if request.user.is_authenticated %}
                        <li class="nav-item mx-3">
                            <a class="nav-link" href="{% url 'kanban:users_detail' request.user.pk %}">{{ request.user.username }}</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link" href="{% url 'kanban:lists_list' %}">リスト一覧</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link" href="{% url 'kanban:cards_list' %}">カード一覧</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
                        </li>

                        {% else %}
                        <li class="nav-item mx-3">
                            <a class="nav-link" href="{% url 'login' %}">ログイン</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link" href="{% url 'kanban:signup' %}">サインアップ</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        <main>
        {% block content %}
        {% endblock %}
        </main>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

kanban/templates/kanban/cards/create.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center">カード作成</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success btn-block">送信</button>
    </form>
</div>
{% endblock %}

kanban/templates/kanban/cards/delete.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">カード削除</h1>
    <form method="post">
        {% csrf_token %}
        <p class="text-center my-5">カード "{{ card.title }}" を本当に削除してもよろしいですか？</p>
        <button type="submit" class="btn btn-danger btn-block mt-5">確認</button>
    </form>
</div>
{% endblock %}

kanban/templates/kanban/cards/detail.html
{% extends "kanban/base.html" %}

{% block content %}

<div class="container" style="width:700px">
    <div class="text-center">
        <h1 class="py-5">カード詳細</h1>
        <table class="table-striped mx-auto mb-5">
            <tr><td class="col-6">タイトル</td><td class="col-6">{{ card.title }}</td></tr>
            <tr><td>詳細</td><td>{{ card.description }}</td></tr>
            <tr><td>リスト名</td><td>{{ card.list.title }}</td></tr>
            <tr><td>ユーザー名</td><td>{{ card.user.username }}</td></tr>
        </table>
            <a class="btn btn-primary" href="{% url 'kanban:cards_update' card.pk  %}" role="button">編集 <i class="fas fa-pen"></i></a>
            <a class="btn btn-danger" href="{% url 'kanban:cards_delete' card.pk  %}" role="button">削除  <i class="far fa-trash-alt fa-xs"></i></a>
    </div>
</div>
{% endblock %}

kanban/templates/kanban/cards/list.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center">カード一覧</h1>
    <a class="btn btn-success btn-block my-3" href="{% url 'kanban:cards_create' %}" role="button">作成</a>
    <div class="card-columns">
        {% for card in card_list %}
        <a href="{% url 'kanban:cards_detail' card.pk %}" class="card">
        <div class="card-body">
            <h5 class="card-title">{{ card.title }}</h5>
            <footer>
            <small class="text-muted">作成者: {{ card.user.username }}</small>
            </footer>
        </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

kanban/templates/kanban/cards/update.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <h1>カード編集</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success btn-block">送信</button>
    </form>
</div>
{% endblock %}

kanban/templates/kanban/home.html
{% extends "kanban/base.html" %}

{% block content %}

<div class="container home">
    <div class="row flex-nowrap">
        {% for list in list_list %}
        <div class="m-3 p-2 list">
            <h4>{{ list.title }}
                <a href="{% url 'kanban:lists_update' list.pk %}" class="text-dark"><i class="fas fa-pen"></i></a>
                <a href="{% url 'kanban:lists_delete' list.pk %}" class="text-dark"><i class="far fa-trash-alt fa-xs"></i></a>
            </h4>

            {% for card in list.card_set.all %}
            <a href="{% url 'kanban:cards_detail' card.pk %}" class="card m-3">
                <div class="card-body">
                    <h5 class="card-title text-success">{{ card.title }}</h5>
                    <footer>
                        <small class="text-muted">作成者: {{ card.user.username }}</small>
                    </footer>
                </div>
            </a>
            {% endfor %}
            <a href="{% url 'kanban:cards_create' %}" class="text-dark"><i class="far fa-plus-square"></i> さらにカードを追加</a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

kanban/templates/kanban/index.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <div class="mx-auto" style="width: 500px;">
        <h1 class="text-center display-3 py-5">To Do List</h1>
        <p class="text-center">Created by Rina</p>
        
        <hr class="my-4">
        <p class="lead text-center py-4">ログインしてネ</p>
        <div class="row justify-content-center">
            <a class="btn btn-success mx-3" href="{% url 'login' %}" role="button">ログイン</a>
            <a class="btn btn-success mx-3" href="{% url 'kanban:signup' %}" role="button">サインアップ</a>
        </div>
    </div>
</div>
{% endblock %}

kanban/templates/kanban/lists/create.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1 class="text-center my-5">リスト作成</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success btn-block mt-5">送信</button>
  </form>
</div>
{% endblock %}

kanban/templates/kanban/lists/delete.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center py-5">リスト削除</h1>
    <form method="post">
        {% csrf_token %}
        <p class="text-center py-3">リスト "{{ list.title }}" を本当に削除してもよろしいですか？</p>
        <button type="submit" class="btn btn-danger btn-block">確認  <i class="far fa-trash-alt fa-xs"></i></button>
    </form>
</div>
{% endblock %}

kanban/templates/kanban/lists/detail.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">リスト詳細</h1>
    <dl class="row text-center">
        <dt class="col-sm-6">タイトル</dt>
        <dd class="col-sm-6">{{ list.title }}</dd>
        <dt class="col-sm-6">ユーザー名</dt>
        <dd class="col-sm-6">{{ list.user.username }}</dd>
    </dl>
    <div class="row justify-content-center mt-5">
        <a class="btn btn-primary mx-3" href="{% url 'kanban:lists_update' list.pk  %}" role="button">編集</a>
        <a class="btn btn-danger mx-3" href="{% url 'kanban:lists_delete' list.pk  %}" role="button">削除</a>
    </div>
</div>

</div>

{% endblock %}

kanban/templates/kanban/lists/list.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
  <h1 class="text-center mb-5">リスト一覧</h1>
  <a class="btn btn-success btn-block mt-3 mb-5 text-center" href="{% url 'kanban:lists_create' %}" role="button">作成</a> 
  <div class="card-columns">
    {% for list in list_list %}
    <a href="{% url 'kanban:lists_detail' list.pk %}" class="card"> 
      <div class="card-body">
        <h5 class="card-title">{{ list.title }}</h5>
        <footer>
          <small class="text-muted">作成者: {{ list.user.username }}</small>
        </footer>
      </div>
    </a> 
    {% endfor %}
  </div>
</div>
{% endblock %}

kanban/templates/kanban/lists/update.html
{% extends "kanban/base.html" %}

{% block content %}

<div class="container">
    <h1 class="text-center mb-5">リスト編集</h1>
    <div class="row justify-content-center">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success btn-block mt-5">送信</button>
        </form>
    </div>
</div>
{% endblock %}

kanban/templates/kanban/signup.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <h1 class="mb-5">サインアップ</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn mt-5 btn-success btn-block">登録</button>
    </form>
</div>
{% endblock %}

kanban/templates/kanban/users/detail.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center py-5">ユーザー詳細</h1>
        <dl class="row text-center mb-5">
            <dt class="col-sm-6">ユーザー名</dt>
            <dd class="col-sm-6">{{ user.username }}</dd>
            <dt class="col-sm-6">姓</dt>
            <dd class="col-sm-6">{{ user.last_name }}</dd>
            <dt class="col-sm-6">名</dt>
            <dd class="col-sm-6">{{ user.first_name }}</dd>
            <dt class="col-sm-6">メールアドレス</dt>
            <dd class="col-sm-6">{{ user.email }}</dd>
        </dl>

    {% if user.pk == request.user.pk %}
    <a class="btn btn-success btn-block m-4" href="{% url 'kanban:users_update' user.pk  %}" role="button">編集</a>
    {% else %}
    <a class="btn btn-success btn-block" href="#" role="button">編集</a>
    {% endif %}
</div>
{% endblock %}

kanban/templates/kanban/users/update.html
{% extends "kanban/base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center">ユーザー編集</h1>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn mt-5 btn-success btn-block">送信</button>
    </form>
</div>
{% endblock %}